// <auto-generated />
using BibliotecaUGB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BibliotecaUGB.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BibliotecaUGB.Models.Autor", b =>
                {
                    b.Property<int>("AutorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ApellidosAutor")
                        .HasColumnType("text");

                    b.Property<string>("EdadAutor")
                        .HasColumnType("text");

                    b.Property<string>("NombresAutor")
                        .HasColumnType("text");

                    b.Property<string>("PaisAutor")
                        .HasColumnType("text");

                    b.HasKey("AutorID");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("BibliotecaUGB.Models.Libro", b =>
                {
                    b.Property<int>("LibroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("AutorID")
                        .HasColumnType("integer");

                    b.Property<string>("CategoriaLibro")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("ISBLibro")
                        .HasColumnType("text");

                    b.Property<string>("PortadaLibro")
                        .HasColumnType("text");

                    b.Property<string>("TituloLibro")
                        .HasColumnType("text");

                    b.HasKey("LibroID");

                    b.ToTable("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
